### ISSUE TITLE
Reconfiguração do Banco

### ISSUE THREAD

**Issue by eilimrib** [fga-eps-mds/2019.2-ArBC-API#7]
### Descrição
Reconfigurar o banco de MongoDB para PostgreSQL devido a problemas de implementação.

### Critérios de Aceitação
- [x] Mudar engine do banco do Django
- [x] Configurar banco

**Comment by Rhuancpq** [comment]
Mudando o banco de dados por falhas na implementação e incompatibilidade na criação do ambiente de desenvolvimento

**Comment by Rhuancpq** [comment]
pode fechar essa issue, o novo banco já está configurado
